const fruits = {
  type: "fruits",
  items: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "kiwi",
    "mango",
    "grape",
    "watermelon",
    "pineapple",
    "peach",
    "pear",
    "plum",
    "cherry",
    "blueberry",
    "raspberry",
    "blackberry",
    "cranberry",
    "pomegranate",
    "apricot",
    "fig",
    "lemon",
    "lime",
    "coconut",
    "avocado",
    "papaya",
    "guava",
    "lychee",
    "passion fruit",
    "dragon fruit",
    "star fruit",
    "kiwano",
    "persimmon",
    "tamarillo",
    "tamarind",
    "quince",
    "date",
    "elderberry",
    "gooseberry",
  ],
};

const vegetables = {
  type: "vegetables",
  items: [
    "carrot",
    "broccoli",
    "cauliflower",
    "cabbage",
    "kale",
    "spinach",
    "lettuce",
    "arugula",
    "swiss chard",
    "collard greens",
    "beet",
    "radish",
    "turnip",
    "rutabaga",
    "parsnip",
    "celery",
    "fennel",
    "asparagus",
    "green bean",
    "snap pea",
    "snow pea",
    "bell pepper",
    "jalapeno",
    "poblano",
    "habanero",
    "cayenne",
    "serrano",
    "onion",
    "shallot",
    "garlic",
    "leek",
    "scallion",
    "potato",
    "sweet potato",
    "yam",
    "squash",
    "zucchini",
    "pumpkin",
    "cucumber",
    "tomato",
    "eggplant",
    "okra",
    "corn",
    "pea",
    "artichoke",
    "brussels sprout",
    "sweet pepper",
    "chili pepper",
    "pumpkin",
    "acorn squash",
    "butternut squash",
    "spaghetti squash",
    "pattypan squash",
    "yellow squash",
    "zephyr squash",
    "delicata squash",
    "kabocha squash",
    "hubbard squash",
    "carnival squash",
    "acorn squash",
    "buttercup squash",
    "gold nugget squash",
    "turban squash",
    "sweet dumpling squash",
    "blue hubbard squash",
    "red kuri squash",
    "banana squash",
    "turban squash",
    "calabaza squash",
    "chayote squash",
    "chinese okra",
    "chinese long bean",
    "daikon",
    "jicama",
    "kohlrabi",
    "lotus root",
    "water chestnut",
    "watercress",
    "bamboo shoot",
    "bean sprout",
    "bok choy",
    "chinese broccoli",
    "chinese cabbage",
    "chinese celery",
  ],
};

const animals = {
  type: "animals",
  items: [
    "dog",
    "cat",
    "bird",
    "fish",
    "rabbit",
    "hamster",
    "guinea pig",
    "ferret",
    "mouse",
    "rat",
    "gerbil",
    "chinchilla",
    "hedgehog",
    "sugar glider",
  ],
};

module.exports = { fruits, vegetables, animals };
